project_id = "aiavwyjuukujdvjzjesu"

[auth.email.template.confirmation]
subject = "Verify your VitalSync account"
content_path = "./templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your VitalSync password"
content_path = "./templates/recovery.html"

[auth.email.template.reauthentication]
subject = "VitalSync security verification"
content_path = "./templates/reauthentication.html"

[auth.email.notification.password_changed]
enabled = true
subject = "Your VitalSync password was changed"
content_path = "./templates/password_changed.html"
