import { callAI } from './api.js';
import { saveDailyLog } from './data.js';
import { requiredFields, todayISO, escapeHTML, toast } from './utils.js';
const questions={sleep_hrs:'How many hours did you sleep last night? (e.g., 7.5)',breakfast:'What did you have for breakfast?',lunch:'What did you have for lunch?',dinner:'What did you have for dinner?',walk_km:'Approximately how many kilometers did you walk today? (e.g., 2.5)',mood:'How was your mood today? (very happy / happy / neutral / sad / very sad)'};
export const chatState={index:0,log:{},history:[],typing:false};
export function resetChat(){chatState.index=0;chatState.log={};chatState.history=[];chatState.typing=false;chatState.history.push({sender:'agent',text:questions[requiredFields[0]]})}
function extract(field,input){const lower=input.trim().toLowerCase();if(field==='sleep_hrs'||field==='walk_km'){const m=lower.match(/(\d+(?:\.\d+)?)/);return m?Number(m[1]):null}if(field==='mood'){if(lower.includes('very happy'))return'veryhappy';if(lower.includes('happy'))return'happy';if(lower.includes('very sad'))return'verysad';if(lower.includes('sad'))return'sad';return'neutral'}return input.trim().slice(0,120)}
export function chatPage(){const loggedToday=(window.__vitalState?.logs||[]).some(x=>x.date===todayISO());const messages=chatState.history.map(m=>`<div class="flex ${m.sender==='user'?'justify-end':'justify-start'}"><div class="chat-bubble ${m.sender}">${escapeHTML(m.text)}</div></div>`).join('');return `<div class="h-full flex flex-col max-w-4xl mx-auto"><h1 class="text-4xl font-bold mb-6">Daily Check-in</h1><div id="chat-messages" class="flex-grow bg-white rounded-lg shadow-inner p-6 flex flex-col space-y-5 overflow-y-auto chat-container">${messages}${chatState.typing?'<div class="text-gray-400">VitalSync is thinking…</div>':''}<div id="chat-end"></div></div><div class="mt-5 flex gap-3"><input id="user-input" class="input-field flex-grow text-lg" placeholder="${loggedToday?'Check-in completed for today.':'Type your answer…'}" ${loggedToday?'disabled':''}/><button id="send-btn" class="btn-primary font-semibold px-6 py-3 rounded-lg" ${loggedToday?'disabled':''}>Send</button>${loggedToday?'<button id="clear-today-small" class="px-4 py-2 rounded-lg bg-gray-100">Clear Today</button>':''}</div></div>`}
export async function sendMessage(render){const input=document.getElementById('user-input');const text=input?.value.trim();if(!text||chatState.typing)return;const field=requiredFields[chatState.index];const value=extract(field,text);if(value===null){toast('Please enter a valid value.','error');return}chatState.log[field]=value;chatState.history.push({sender:'user',text});chatState.index++;input.value='';chatState.typing=true;render();try{if(chatState.index>=requiredFields.length){chatState.log.date=todayISO();const saved=await saveDailyLog(chatState.log);window.__vitalState.logs=[saved,...(window.__vitalState.logs||[]).filter(x=>x.date!==saved.date)];chatState.history.push({sender:'agent',text:'Thanks — your daily check-in is complete and securely saved.'});try{const ai=await callAI({action:'chat',prompt:`Confirm this daily check-in in one short, friendly message. Do not diagnose. Data: ${JSON.stringify(saved)}`,history:chatState.history.slice(-6).map(x=>({role:x.sender==='agent'?'model':'user',text:x.text}))});chatState.history.push({sender:'agent',text:ai})}catch{} }else{const next=requiredFields[chatState.index];chatState.history.push({sender:'agent',text:questions[next]})}}catch(e){chatState.history.push({sender:'agent',text:`I couldn't save this check-in: ${e.message}`})}finally{chatState.typing=false;render();setTimeout(()=>document.getElementById('chat-end')?.scrollIntoView({behavior:'smooth'}),50)}}
